import {
  describe,
  expect,
  test
} from 'vitest';

import pkgInfo from '../package.json';
import {
  createModuleGen
} from '../src';

describe(`${pkgInfo.name}@${pkgInfo.version}`, () => {
  test('createModuleGen', () => {
    const moduleGen = createModuleGen('module-css-var-color.test');
    
    moduleGen.push(':root {');
    moduleGen.push(1, '--kf-color--gray-0: #fff;');
    moduleGen.push(1, '--kf-color--gray-c: #000;');
    moduleGen.push('}');
    
    expect(moduleGen.generate()).toEqual(`/* ===================== *
 * 🚨 No Manual Edit 🚨
 * Generated by module-css-var-color.test
 * ===================== */
:root {
  --kf-color--gray-0: #fff;
  --kf-color--gray-c: #000;
}`);
  });
});
