// 不能拆出去然后 import，会报错 ERR_REQUIRE_CYCLE_MODULE
const GROUPS = [
  // Compose rules from other selectors in CSS Modules.
  // @see https://github.com/css-modules/css-modules#composition
  ['composes'],
  // Must be first (unless using the above).
  ['all'],
  [ // content
    'content',
    'content-visibility'
  ],
  [ // positioning
    'position',
    'top',
    'right',
    'bottom',
    'left',
    'inset',
    'inset-block',
    'inset-block-start',
    'inset-block-end',
    'inset-inline',
    'inset-inline-start',
    'inset-inline-end',
    'zoom',
    'z-index',
    'isolation',
    'transform-origin',
    'transform-box',
    'transform-style',
    'transform',
    'translate',
    'rotate',
    'scale',
    'offset-path',
    'offset-distance',
    'offset-rotate'
  ], [ // layout
    'display',
    'table-layout',
    'container',
    'container-name',
    'container-type',
    'flex',
    'flex-flow',
    'flex-basis',
    'flex-direction',
    'flex-grow',
    'flex-shrink',
    'flex-wrap',
    'align-content',
    'align-items',
    'align-self',
    'justify-content',
    'justify-items',
    'justify-self',
    'grid',
    'grid-area',
    'grid-auto-columns',
    'grid-auto-flow',
    'grid-auto-rows',
    'grid-column',
    'grid-column-end',
    'grid-column-gap',
    'grid-column-start',
    'grid-gap',
    'grid-row',
    'grid-row-end',
    'grid-row-gap',
    'grid-row-start',
    'grid-template',
    'grid-template-areas',
    'grid-template-columns',
    'grid-template-rows',
    'order',
    'orphans',
    'columns',
    'column-count',
    'column-width',
    'column-fill',
    'column-rule',
    'column-rule-color',
    'column-rule-style',
    'column-rule-width',
    'column-span',
    'column-gap',
    'break-inside',
    'break-before',
    'break-after',
    'row-gap',
    'gap',
    'size',
    'direction',
    'unicode-bidi',
    'float',
    'clear',
    'contain',
    'overflow',
    'overflow-x',
    'overflow-y',
    'overflow-block',
    'overflow-inline',
    'overflow-clip-margin',
    'overscroll-behavior',
    'overscroll-behavior-x',
    'overscroll-behavior-y',
    'overscroll-behavior-inline',
    'overscroll-behavior-block',
    'empty-cells',
    'box-orient',
    'line-clamp',
    'place-content',
    'place-items',
    'place-self',
    'shape-outside',
    'shape-image-threshold',
    'shape-margin',
    'widows'
  ], [ // boxModel
    'margin',
    'margin-top',
    'margin-right',
    'margin-bottom',
    'margin-left',
    'margin-block',
    'margin-block-start',
    'margin-block-end',
    'margin-inline',
    'margin-inline-start',
    'margin-inline-end',
    'padding',
    'padding-top',
    'padding-right',
    'padding-bottom',
    'padding-left',
    'padding-block',
    'padding-block-start',
    'padding-block-end',
    'padding-inline',
    'padding-inline-start',
    'padding-inline-end',
    'box-sizing',
    'width',
    'min-width',
    'max-width',
    'height',
    'min-height',
    'max-height',
    'block-size',
    'min-block-size',
    'max-block-size',
    'inline-size',
    'min-inline-size',
    'max-inline-size',
    'aspect-ratio'
  ], [ // typography
    'writing-mode',
    'font',
    'font-family',
    'font-size',
    'font-feature-settings',
    'font-variation-settings',
    'font-optical-sizing',
    'font-weight',
    'font-style',
    'font-display',
    'font-kerning',
    'font-variant',
    'font-variant-ligatures',
    'font-variant-caps',
    'font-variant-alternates',
    'font-variant-numeric',
    'font-variant-east-asian',
    'font-variant-position',
    'font-size-adjust',
    'font-stretch',
    'font-effect',
    'font-emphasize',
    'font-emphasize-position',
    'font-emphasize-style',
    'font-smoothing',
    '-webkit-font-smoothing',
    '-moz-osx-font-smoothing',
    'font-smooth',
    'ruby-position',
    'hyphens',
    'color',
    'text-align',
    'text-align-last',
    'text-emphasis',
    'text-emphasis-color',
    'text-emphasis-style',
    'text-emphasis-position',
    'text-decoration',
    'text-decoration-color',
    'text-decoration-line',
    'text-decoration-style',
    'text-decoration-thickness',
    'text-decoration-skip-ink',
    'text-underline-position',
    'text-underline-offset',
    'text-indent',
    'text-justify',
    'text-outline',
    'text-overflow',
    'text-overflow-ellipsis',
    'text-overflow-mode',
    'text-shadow',
    'text-transform',
    'text-wrap',
    'text-size-adjust',
    'text-combine-upright',
    'text-orientation',
    'text-rendering',
    '-webkit-text-fill-color',
    '-webkit-text-stroke-color',
    'line-height',
    'line-break',
    'line-gap-override',
    'letter-spacing',
    'word-break',
    'word-spacing',
    'word-wrap',
    'overflow-wrap',
    'tab-size',
    'white-space',
    'vertical-align',
    'paint-order',
    'hanging-punctuation',
    'list-style',
    'list-style-position',
    'list-style-type',
    'list-style-image',
    'src',
    'unicode-range',
    'ascent-override',
    'descent-override'
  ], [ // appearance
    'appearance',
    'visibility',
    'color-scheme',
    'forced-color-adjust',
    'accent-color',
    'perspective',
    'perspective-origin',
    'backface-visibility',
    'opacity',
    'object-fit',
    'object-position',
    'image-orientation',
    'background',
    'background-color',
    'background-image',
    'background-repeat',
    'background-repeat-x',
    'background-repeat-y',
    'background-attachment',
    'background-position',
    'background-position-x',
    'background-position-y',
    'background-clip',
    'background-origin',
    'background-size',
    'background-blend-mode',
    'clip',
    'clip-path',
    'filter',
    'backdrop-filter',
    'box-decoration-break',
    'border',
    'border-color',
    'border-style',
    'border-width',
    'border-top',
    'border-top-color',
    'border-top-style',
    'border-top-width',
    'border-right',
    'border-right-color',
    'border-right-style',
    'border-right-width',
    'border-bottom',
    'border-bottom-color',
    'border-bottom-style',
    'border-bottom-width',
    'border-left',
    'border-left-color',
    'border-left-style',
    'border-left-width',
    'border-block',
    'border-block-color',
    'border-block-style',
    'border-block-width',
    'border-block-start',
    'border-block-start-color',
    'border-block-start-style',
    'border-block-start-width',
    'border-block-end',
    'border-block-end-color',
    'border-block-end-style',
    'border-block-end-width',
    'border-inline',
    'border-inline-color',
    'border-inline-style',
    'border-inline-width',
    'border-inline-start',
    'border-inline-start-color',
    'border-inline-start-style',
    'border-inline-start-width',
    'border-inline-end',
    'border-inline-end-color',
    'border-inline-end-style',
    'border-inline-end-width',
    'border-radius',
    'border-top-left-radius',
    'border-top-right-radius',
    'border-bottom-right-radius',
    'border-bottom-left-radius',
    'border-start-start-radius',
    'border-start-end-radius',
    'border-end-start-radius',
    'border-end-end-radius',
    'border-image',
    'border-image-source',
    'border-image-slice',
    'border-image-width',
    'border-image-outset',
    'border-image-repeat',
    'border-spacing',
    'border-collapse',
    'outline',
    'outline-color',
    'outline-style',
    'outline-width',
    'outline-offset',
    'box-shadow',
    'mix-blend-mode',
    'caret-color',
    'box-decoration-break',
    '-webkit-box-decoration-break'
  ], [ // interaction
    'pointer-events',
    'touch-action',
    'will-change',
    'cursor',
    'caption-side',
    'quotes',
    'counter-set',
    'counter-increment',
    'counter-reset',
    'resize',
    'user-select',
    'overflow-anchor',
    'nav-index',
    'nav-up',
    'nav-right',
    'nav-down',
    'nav-left',
    'scroll-behavior',
    'scrollbar-color',
    'scrollbar-width',
    'scrollbar-gutter',
    'scroll-margin',
    'scroll-margin-block',
    'scroll-margin-block-start',
    'scroll-margin-block-end',
    'scroll-margin-inline',
    'scroll-margin-inline-start',
    'scroll-margin-inline-end',
    'scroll-margin-top',
    'scroll-margin-right',
    'scroll-margin-bottom',
    'scroll-margin-left',
    'scroll-padding',
    'scroll-padding-block',
    'scroll-padding-block-start',
    'scroll-padding-block-end',
    'scroll-padding-inline',
    'scroll-padding-inline-start',
    'scroll-padding-inline-end',
    'scroll-padding-top',
    'scroll-padding-right',
    'scroll-padding-bottom',
    'scroll-padding-left',
    'scroll-snap-type',
    'scroll-snap-align',
    'scroll-snap-stop',
    'scroll-timeline',
    'scroll-timeline-name',
    'scroll-timeline-axis',
    'contain-intrinsic-size',
    'contain-intrinsic-width',
    'contain-intrinsic-height',
    'contain-intrinsic-inline-size',
    'contain-intrinsic-block-size',
    'speak',
    'speak-as'
  ], [ // svg
    'alignment-baseline',
    'baseline-shift',
    'dominant-baseline',
    'text-anchor',
    'cx',
    'cy',
    'd',
    'r',
    'rx',
    'ry',
    'fill',
    'fill-opacity',
    'fill-rule',
    'flood-color',
    'flood-opacity',
    'stop-color',
    'stop-opacity',
    'stroke',
    'stroke-dasharray',
    'stroke-dashoffset',
    'stroke-linecap',
    'stroke-linejoin',
    'stroke-miterlimit',
    'stroke-opacity',
    'stroke-width',
    'vector-effect',
    'color-interpolation',
    'color-interpolation-filters',
    'color-profile',
    'color-rendering',
    'image-rendering',
    'lighting-color',
    'marker-start',
    'marker-mid',
    'marker-end',
    'mask',
    'mask-type',
    'shape-rendering',
    'clip-rule'
  ], [ // transition
    'transition',
    'transition-delay',
    'transition-timing-function',
    'transition-duration',
    'transition-property',
    'animation',
    'animation-name',
    'animation-duration',
    'animation-play-state',
    'animation-timing-function',
    'animation-fill-mode',
    'animation-delay',
    'animation-iteration-count',
    'animation-direction',
    'animation-timeline',
    'timeline-scope',
    'view-timeline',
    'view-timeline-name',
    'view-timeline-axis',
    'view-timeline-inset',
    'view-transition-name'
  ]
];

/** @type {import('stylelint').Config} */
export default {
  plugins: ['stylelint-order'],
  rules: {
    'order/order': [[{
      type: 'at-rule',
      name: 'import'
    }, {
      type: 'at-rule',
      name: 'forward'
    }, {
      type: 'at-rule',
      name: 'use'
    },
      'dollar-variables',
      'at-variables',
      'custom-properties',
      {
        type: 'at-rule',
        name: 'custom-media'
      }, {
        type: 'at-rule',
        name: 'function'
      }, {
        type: 'at-rule',
        name: 'mixin'
      }, {
        type: 'at-rule',
        name: 'extend'
      },
      'declarations',
      {
        type: 'rule',
        selector: /^&::[\w-]+/,
        hasBlock: true
      },
      'rules',
      {
        type: 'at-rule',
        name: 'media',
        hasBlock: true
      }], {
      severity: 'error'
    }],
    'order/properties-order': [GROUPS.map(properties => ({
      noEmptyLineBetween: true,
      properties
    })), {
      severity: 'error',
      unspecified: 'ignore', // 让 styled-components 的 mixin 可以按需要放置
      emptyLineBeforeUnspecified: 'always',
      emptyLineMinimumPropertyThreshold: 5
    }]
  }
};