import {
  COLOR_LIGHT,
  COLOR_DARK
} from '../color-base';

export const COLOR_FORM_CONTROL = {
  FGC: COLOR_LIGHT.GRAY_PRIMARY,
  FGC_DISABLED: COLOR_LIGHT.GRAY_DISABLED,
  BDC: COLOR_LIGHT.GRAY_TERTIARY_BD,
  BDC_HOVER: COLOR_LIGHT.GRAY_SECONDARY_BD,
  BDC_ACTIVE: COLOR_LIGHT.GRAY_PRIMARY_BD,
  BDC_FOCUS: 'hsl(240 50% 60%)',
  BDC_DISABLED: COLOR_LIGHT.GRAY_DISABLED_BD,
  BGC: COLOR_LIGHT.GRAY_PRIMARY_BG,
  BGC_HOVER: COLOR_LIGHT.GRAY_SECONDARY_BG,
  BGC_ACTIVE: COLOR_LIGHT.GRAY_TERTIARY_BG,
  BGC_DISABLED: COLOR_LIGHT.GRAY_DISABLED_BG
};

export const COLOR_FORM_CONTROL_DARK = {
  FGC: COLOR_DARK.GRAY_PRIMARY,
  FGC_DISABLED: COLOR_DARK.GRAY_DISABLED,
  BDC: COLOR_DARK.GRAY_TERTIARY_BD,
  BDC_HOVER: COLOR_DARK.GRAY_SECONDARY_BD,
  BDC_ACTIVE: COLOR_DARK.GRAY_PRIMARY_BD,
  BDC_FOCUS: 'hsl(240 50% 60%)',
  BDC_DISABLED: COLOR_DARK.GRAY_DISABLED_BD,
  BGC: COLOR_DARK.GRAY_PRIMARY_BG,
  BGC_HOVER: COLOR_DARK.GRAY_SECONDARY_BG,
  BGC_ACTIVE: COLOR_DARK.GRAY_TERTIARY_BG,
  BGC_DISABLED: COLOR_DARK.GRAY_DISABLED_BG
};
