import {
  COLOR_LIGHT,
  COLOR_DARK
} from '../color-base';

export const COLOR_TABLE = {
  BGC_TH: COLOR_LIGHT.GRAY_SECONDARY_BG,
  BGC_TD: COLOR_LIGHT.GRAY_PRIMARY_BG,
  BDC: COLOR_LIGHT.GRAY_TERTIARY_BD
};

export const COLOR_TABLE_DARK = {
  BGC_TH: COLOR_DARK.GRAY_SECONDARY_BG,
  BGC_TD: COLOR_DARK.GRAY_PRIMARY_BG,
  BDC: COLOR_DARK.GRAY_TERTIARY_BD
};
