import {
  IColorText,
  IColorBg,
  IColorBorder,
  IColorButton
} from '../types';

/**
 * 按钮，需要定义
 * * 文字色
 * * 背景色
 * * 边框色
 *
 * 每种色需要定义如下状态：
 * * 正常
 * * `:hover` + `:focus`
 * * `:active`
 * * `:disabled`
 */
export default function createConstColorButton(fg: IColorText, bg: IColorBg, bd: IColorBorder): IColorButton {
  return {
    /**
     * 默认按钮 - 空心
     *
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 黑字 | 白底 | 灰边
     * HOVER | 黑字 | 浅灰底 | 灰边
     * 禁用 | 灰字 | 浅灰底 | 灰边
     */
    BUTTON_DEFAULT_TEXT: fg.TEXT_SECONDARY,
    BUTTON_DEFAULT_BG: bg.BG_TRANSPARENT,
    BUTTON_DEFAULT_BORDER: bd.BORDER_SECONDARY,
    BUTTON_DEFAULT_TEXT_HOVER: fg.TEXT_PRIMARY,
    BUTTON_DEFAULT_BG_HOVER: bg.BG_SECONDARY,
    BUTTON_DEFAULT_BORDER_HOVER: bd.BORDER_SECONDARY,
    BUTTON_DEFAULT_TEXT_ACTIVE: fg.TEXT_PRIMARY,
    BUTTON_DEFAULT_BG_ACTIVE: bg.BG_SECONDARY,
    BUTTON_DEFAULT_BORDER_ACTIVE: bd.BORDER_SECONDARY,
    BUTTON_DEFAULT_TEXT_DISABLED: fg.TEXT_DISABLED,
    BUTTON_DEFAULT_BG_DISABLED: bg.BG_TRANSPARENT,
    BUTTON_DEFAULT_BORDER_DISABLED: bd.BORDER_DISABLED,
    
    /**
     * 一级按钮
     *
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 白字 | 蓝底 | 蓝边
     * HOVER | 白字 | 蓝底 | 蓝边
     * 禁用 | 白字 | 灰底 | 灰边
     */
    BUTTON_PRIMARY_TEXT: fg.TEXT_WHITE,
    BUTTON_PRIMARY_BG: bg.BG_ACCENT,
    BUTTON_PRIMARY_BORDER: bd.BORDER_ACCENT,
    BUTTON_PRIMARY_TEXT_HOVER: fg.TEXT_WHITE,
    BUTTON_PRIMARY_BG_HOVER: bg.BG_ACCENT_HOVER,
    BUTTON_PRIMARY_BORDER_HOVER: bd.BORDER_ACCENT_HOVER,
    BUTTON_PRIMARY_TEXT_ACTIVE: fg.TEXT_WHITE,
    BUTTON_PRIMARY_BG_ACTIVE: bg.BG_ACCENT_ACTIVE,
    BUTTON_PRIMARY_BORDER_ACTIVE: bd.BORDER_ACCENT_ACTIVE,
    BUTTON_PRIMARY_TEXT_DISABLED: fg.TEXT_WHITE,
    BUTTON_PRIMARY_BG_DISABLED: bg.BG_DISABLED,
    BUTTON_PRIMARY_BORDER_DISABLED: bd.BORDER_DISABLED,
    
    /**
     * 二级按钮
     *
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 黑字 | 灰底 | 无边
     * HOVER | 黑字 | 灰底+ | 无边
     * 禁用 | 灰字 | 无底 | 无边
     */
    BUTTON_SECONDARY_TEXT: fg.TEXT_SECONDARY,
    BUTTON_SECONDARY_BG: bg.BG_SECONDARY,
    BUTTON_SECONDARY_BORDER: bd.BORDER_TRANSPARENT,
    BUTTON_SECONDARY_TEXT_HOVER: fg.TEXT_PRIMARY,
    BUTTON_SECONDARY_BG_HOVER: bg.BG_TERTIARY,
    BUTTON_SECONDARY_BORDER_HOVER: bd.BORDER_TRANSPARENT,
    BUTTON_SECONDARY_TEXT_ACTIVE: fg.TEXT_PRIMARY,
    BUTTON_SECONDARY_BG_ACTIVE: bg.BG_TERTIARY,
    BUTTON_SECONDARY_BORDER_ACTIVE: bd.BORDER_TRANSPARENT,
    BUTTON_SECONDARY_TEXT_DISABLED: fg.TEXT_DISABLED,
    BUTTON_SECONDARY_BG_DISABLED: bg.BG_TRANSPARENT,
    BUTTON_SECONDARY_BORDER_DISABLED: bd.BORDER_TRANSPARENT,
    
    /**
     * 三级按钮
     *
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 黑字 | 无底 | 无边
     * HOVER | 黑字 | 灰底 | 无边
     * 禁用 | 灰字 | 无底 | 无边
     */
    BUTTON_TERTIARY_TEXT: fg.TEXT_SECONDARY,
    BUTTON_TERTIARY_BG: bg.BG_TRANSPARENT,
    BUTTON_TERTIARY_BORDER: bd.BORDER_TRANSPARENT,
    BUTTON_TERTIARY_TEXT_HOVER: fg.TEXT_PRIMARY,
    BUTTON_TERTIARY_BG_HOVER: bg.BG_SECONDARY,
    BUTTON_TERTIARY_BORDER_HOVER: bd.BORDER_TRANSPARENT,
    BUTTON_TERTIARY_TEXT_ACTIVE: fg.TEXT_PRIMARY,
    BUTTON_TERTIARY_BG_ACTIVE: bg.BG_SECONDARY,
    BUTTON_TERTIARY_BORDER_ACTIVE: bd.BORDER_TRANSPARENT,
    BUTTON_TERTIARY_TEXT_DISABLED: fg.TEXT_DISABLED,
    BUTTON_TERTIARY_BG_DISABLED: bg.BG_SECONDARY,
    BUTTON_TERTIARY_BORDER_DISABLED: bd.BORDER_TRANSPARENT,
    
    /**
     * 危险警告按钮
     *
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 白字 | 红底 | 红边
     * HOVER | 白字 | 红底 | 红边
     * ACTIVE | 白字 | 深红底 | 红边
     * 禁用 | 白字 | 灰底 | 灰边
     */
    BUTTON_DANGER_TEXT: fg.TEXT_WHITE,
    BUTTON_DANGER_BG: bg.BG_DANGER,
    BUTTON_DANGER_BORDER: bd.BORDER_DANGER,
    BUTTON_DANGER_TEXT_HOVER: fg.TEXT_WHITE,
    BUTTON_DANGER_BG_HOVER: bg.BG_DANGER,
    BUTTON_DANGER_BORDER_HOVER: bd.BORDER_DANGER,
    BUTTON_DANGER_TEXT_ACTIVE: fg.TEXT_WHITE,
    BUTTON_DANGER_BG_ACTIVE: bg.BG_DANGER,
    BUTTON_DANGER_BORDER_ACTIVE: bd.BORDER_DANGER,
    BUTTON_DANGER_TEXT_DISABLED: fg.TEXT_WHITE,
    BUTTON_DANGER_BG_DISABLED: bg.BG_DISABLED,
    BUTTON_DANGER_BORDER_DISABLED: bd.BORDER_DISABLED,
    
    /**
     * 链接按钮
     *
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 蓝字 | 无底 | 无边
     * HOVER | 蓝字 | 无底 | 无边
     * 禁用 | 灰字 | 无底 | 无边
     */
    BUTTON_LINK_TEXT: fg.TEXT_ACCENT,
    BUTTON_LINK_BG: bg.BG_TRANSPARENT,
    BUTTON_LINK_BORDER: bd.BORDER_TRANSPARENT,
    BUTTON_LINK_TEXT_HOVER: fg.TEXT_ACCENT_HOVER,
    BUTTON_LINK_BG_HOVER: bg.BG_TRANSPARENT,
    BUTTON_LINK_BORDER_HOVER: bd.BORDER_TRANSPARENT,
    BUTTON_LINK_TEXT_ACTIVE: fg.TEXT_ACCENT_HOVER,
    BUTTON_LINK_BG_ACTIVE: bg.BG_TRANSPARENT,
    BUTTON_LINK_BORDER_ACTIVE: bd.BORDER_TRANSPARENT,
    BUTTON_LINK_TEXT_DISABLED: fg.TEXT_DISABLED,
    BUTTON_LINK_BG_DISABLED: bg.BG_TRANSPARENT,
    BUTTON_LINK_BORDER_DISABLED: bd.BORDER_TRANSPARENT,
    
    /**
     * 文字按钮
     *
     * 态\色 | 字 | 底 | 边
     * :-- | :-- | :-- | :--
     * 正常 | 黑字 | 无底 | 无边
     * HOVER | 黑字 | 无底 | 无边
     * 禁用 | 灰字 | 无底 | 无边
     */
    BUTTON_TEXT_TEXT: fg.TEXT_SECONDARY,
    BUTTON_TEXT_BG: bg.BG_TRANSPARENT,
    BUTTON_TEXT_BORDER: bd.BORDER_TRANSPARENT,
    BUTTON_TEXT_TEXT_HOVER: fg.TEXT_PRIMARY,
    BUTTON_TEXT_BG_HOVER: bg.BG_TRANSPARENT,
    BUTTON_TEXT_BORDER_HOVER: bd.BORDER_TRANSPARENT,
    BUTTON_TEXT_TEXT_ACTIVE: fg.TEXT_PRIMARY,
    BUTTON_TEXT_BG_ACTIVE: bg.BG_TRANSPARENT,
    BUTTON_TEXT_BORDER_ACTIVE: bd.BORDER_TRANSPARENT,
    BUTTON_TEXT_TEXT_DISABLED: fg.TEXT_DISABLED,
    BUTTON_TEXT_BG_DISABLED: bg.BG_TRANSPARENT,
    BUTTON_TEXT_BORDER_DISABLED: bd.BORDER_TRANSPARENT
  };
}
