export enum EAction {
  PUSH_ACTIVE_CODE,
  PULL_ACTIVE_CODE,
  UPDATE_ACTIVE_MODIFIERS,
  SET_CAPS_LOCK,
  SET_KEY_DETAILS
}

export enum EKeyboardCode {
  F1 = 'F1',
  F2 = 'F2',
  F3 = 'F3',
  F4 = 'F4',
  F5 = 'F5',
  F6 = 'F6',
  F7 = 'F7',
  F8 = 'F8',
  F9 = 'F9',
  F10 = 'F10',
  F11 = 'F11',
  F12 = 'F12',
  D1 = 'Digit1',
  D2 = 'Digit2',
  D3 = 'Digit3',
  D4 = 'Digit4',
  D5 = 'Digit5',
  D6 = 'Digit6',
  D7 = 'Digit7',
  D8 = 'Digit8',
  D9 = 'Digit9',
  D0 = 'Digit0',
  A = 'KeyA',
  B = 'KeyB',
  C = 'KeyC',
  D = 'KeyD',
  E = 'KeyE',
  F = 'KeyF',
  G = 'KeyG',
  H = 'KeyH',
  I = 'KeyI',
  J = 'KeyJ',
  K = 'KeyK',
  L = 'KeyL',
  M = 'KeyM',
  N = 'KeyN',
  O = 'KeyO',
  P = 'KeyP',
  Q = 'KeyQ',
  R = 'KeyR',
  S = 'KeyS',
  T = 'KeyT',
  U = 'KeyU',
  V = 'KeyV',
  W = 'KeyW',
  X = 'KeyX',
  Y = 'KeyY',
  Z = 'KeyZ',
  
  BACKSLASH = 'Backslash',
  BACKQUOTE = 'Backquote',
  MINUS = 'Minus',
  EQUAL = 'Equal',
  BRACKET_LEFT = 'BracketLeft',
  BRACKET_RIGHT = 'BracketRight',
  SEMICOLON = 'Semicolon',
  QUOTE = 'Quote',
  COMMA = 'Comma',
  PERIOD = 'Period',
  SLASH = 'Slash',
  
  ESC = 'Escape',
  CAPS_LOCK = 'CapsLock',
  BACKSPACE = 'Backspace',
  DELETE = 'Delete',
  TAB = 'Tab',
  SPACE = 'Space',
  ENTER = 'Enter',
  
  CONTROL_LEFT = 'ControlLeft',
  CONTROL_RIGHT = 'ControlRight',
  ALT_LEFT = 'AltLeft',
  ALT_RIGHT = 'AltRight',
  SHIFT_LEFT = 'ShiftLeft',
  SHIFT_RIGHT = 'ShiftRight',
  META_LEFT = 'MetaLeft',
  META_RIGHT = 'MetaRight',
  ARROW_LEFT = 'ArrowLeft',
  ARROW_UP = 'ArrowUp',
  ARROW_RIGHT = 'ArrowRight',
  ARROW_DOWN = 'ArrowDown',
  
  POWER = 'Power', // fake
  FN = 'TheFn' // fake
}
