export enum EAction {
  SET_EVER_INIT,
  SET_DOM_CONTAINER,
  SET_DOM_MARKING,
  LOOP_OPTION_EDITABLE,
  TOGGLE_OPTION_DEBUG_EVENTS,
  SET_MARKING_INSTANCE,
  SET_MARKING_STATS,
  TOGGLE_FULLSCREEN
}
